sam_internal.h : code2base[512] -> code2base[512+1] for end of string ]
When compiling `sam_internal.h` against g++ (I need nibble2base ) there is an error because the '\0' is missing.

```
sam_internal.h:73:9: error: initializer-string for ‘const char [512]’ is too long [-fpermissive]
```

this PR changes `512` to `513`.